### ISSUE TITLE
My loop isnt looping

### ISSUE THREAD

**Issue by scrapjo** [coding-pythonx/supermarket-cashier#2]
i have written the code, can someone please help me out, what is wrong? The issue is that Im just able to input one product, doesnt matter what product. I input the product, it asks for quantity, and then jumpes to ask for what membership i have, im not able to put in another product on the same order:

```
This function will let you input all the products bought one by one
def enterProducts():
    buyingData = {}
    enterDetails = True
    while enterDetails:
        details = input('Press A to add product and Q to quit: ')
        if details == 'A':
            product = input('Enter product: ')
            quantity = int(input('Enter quantity: '))
            buyingData.update({product: quantity})
        elif details == 'Q':
            enterDetails = False
        else:
            print('Please select a correct option')
        return buyingData

#This function gives the subtotal of a single product as per its price and quantity.
def getPrice(product, quantity):
    priceData = {
        'Bisquit': 3,
        'Chicken': 5,
        'Egg': 1,
        'Fish': 3,
        'Coke': 2,
        'Bread': 2,
        'Apple': 3,
        'Onion': 3
    }
    subtotal = priceData[product] * quantity
    print(product + ':$' +
          str(priceData[product]) + 'x' + str(quantity) + '=' + str(subtotal))
    return subtotal


#this part handles the discount, based on the membership
def getDiscount(billAmount, membership):
    discount = 0
    if billAmount >= 25:
        if membership == 'Gold':
            billAmount = billAmount *0.80
            discount = 20
        elif membership == 'Silver':
            billAmount = billAmount *0.90
            discount = 10
        elif membership == 'Bronze':
            billAmount = billAmount *0.95
            discount = 5
        print(str(discount)+ '% off for '+ membership + '' +'membership on total ammount: $' + str(billAmount))
    else:
        print('No discount on amount less than $25')
    return billAmount

#This section is about the final bill
def makeBill(buyingData, membership):
    billAmount = 0
    for key, value in buyingData.items():
        billAmount += getPrice(key, value)
    billAmount = getDiscount(billAmount, membership)
    print('The discounted amount is $' + str(billAmount))

buyingData = enterProducts()
membership = input('Enter customer membership: ')
makeBill(buyingData, membership)

```
`

**Comment by hydr0phobia** [comment]
Hello, the problem seems to be that you have idented the block of code   - return buyingData in the first function at the same level as the if statements. You need to delete that identation to make that return buyingData at the same level as the while loop

```
`def enterProducts():
    buyingData = {}
    enterDetails = True
    while enterDetails:
        details = input('Press A to add product and Q to quit: ')
        if details == 'A':
            product = input('Enter product: ')
            quantity = int(input('Enter quantity: '))
            buyingData.update({product: quantity})
        elif details == 'Q':
            enterDetails = False
        else:
            print('Please select a correct option')
    return buyingData`
```


Also i have noticed that you have written the product 'Bisquit' with a 'q'.  So when entering the products you have to write it exaclty the same way. Hope this helped you to understand it.

**Comment by scrapjo** [comment]
> Hello, the problem seems to be that you have idented the block of code - return buyingData in the first function at the same level as the if statements. You need to delete that identation to make that return buyingData at the same level as the while loop
> 
> ```
> `def enterProducts():
>     buyingData = {}
>     enterDetails = True
>     while enterDetails:
>         details = input('Press A to add product and Q to quit: ')
>         if details == 'A':
>             product = input('Enter product: ')
>             quantity = int(input('Enter quantity: '))
>             buyingData.update({product: quantity})
>         elif details == 'Q':
>             enterDetails = False
>         else:
>             print('Please select a correct option')
>     return buyingData`
> ```
> 
> Also i have noticed that you have written the product 'Bisquit' with a 'q'. So when entering the products you have to write it exaclty the same way. Hope this helped you to understand it.

Thank you very much, i have twisted my brain out and in and some part of me told me that it had to be something easy, but i couldn't find out what.

Thank you again, I have corrected the spelling issue and the indentation, and now it works like it should. Hope you have a nice day.
